server:
  port: 28500

spring:
  application:
    name: githubdata
  flyway:
    enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/githubrepo_db?serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    tomcat:
      validation-query: SELECT 1
      test-on-borrow: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

githubdata:
  swagger:
    enable:true

mybatis:
  configuration:
    map-underscore-to-camel-case: true